"""Add instagram

Revision ID: 88d10304ff3f
Revises: e0a51724e530
Create Date: 2025-07-29 12:49:49.167819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d10304ff3f'
down_revision: Union[str, None] = 'e0a51724e530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_accounts',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cookies', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('instagram_accounts_pkey'))
    )
    op.create_index(op.f('instagram_accounts_id_idx'), 'instagram_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('instagram_accounts_id_idx'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    # ### end Alembic commands ###
